# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/little_ai',
                'doc_host': 'https://darkknightxi.github.io',
                'git_url': 'https://github.com/darkknightxi/little_ai',
                'lib_path': 'little_ai'},
  'syms': {'little_ai.core': {'little_ai.core.foo': ('core.html#foo', 'little_ai/core.py')}}}
